sudo: required
language: python
python:
    - "3.6"

services:
  - mysql
  - mongodb

script:
    - pip install tox
    - tox -e coverage,flake8

after_success:
- codecov

notifications:
  email: false