sudo: required
language: python
python:
    - "3.6"

services:
  - mysql
  - mongodb


script:
    - pip install codecov
    - pip install tox
    - tox -e coverage

after_success:
- codecov

notifications:
  email: false